print("UTS Dasar Pemrograman")
print("-----------------------------------------------")
print("Nama: Dicky Setiawan")
print("NIM: A11.2020.13089")
print("Kelompok: A11.4114")
print("----------------------------------------------")
print("Soal Nomor 2")
print("----------------------------------------------")

print("Inputkan Nilai-nilai Array A")
num1= int(input("Array A ke-1 :"))
num2= int(input("Array A ke-2 :"))
num3= int(input("Array A ke-3 :"))
num4= int(input("Array B ke-4 :"))
print("Inputan Nilai-nilai Array B")
num5= int(input("Array B ke-1 :"))
num6= int(input("Array B ke-2 :"))
num7= int(input("Array B ke-3 :"))
num8= int(input("Array B ke-4 :"))
print
print("array1",num1,num2,num3,num4)
print("array2",num5,num6,num7,num8)
print("hasil",num2+num6,'   ',num4+num8)
print("jumlah",(num2+num6)+(num4+num8))